-- Demo/seed data for development & preview purposes only.
-- Clearly demo: companies and jobs below are illustrative, not real employer postings.

insert into companies (name, slug) values
  ('Al Falak Engineering Group','al-falak-engineering-group'),
  ('Gulf Horizon Construction','gulf-horizon-construction'),
  ('Desert Rose Hospitality','desert-rose-hospitality'),
  ('NorthStar Oil & Gas Services','northstar-oil-gas-services'),
  ('Bright Path Healthcare','bright-path-healthcare'),
  ('Apex Logistics Gulf','apex-logistics-gulf'),
  ('Prime Facilities Management','prime-facilities-management'),
  ('TechNova Solutions','technova-solutions'),
  ('Al Waha Trading LLC','al-waha-trading-llc'),
  ('Skyline Architects','skyline-architects'),
  ('SecureGuard Services','secureguard-services'),
  ('Al Reem Financial Group','al-reem-financial-group');

insert into jobs (
  reference, title, slug, company_id, category_id, country_id, location_id,
  employment_type, experience_min, experience_max, salary_min, salary_max, salary_currency, salary_is_visible,
  description, responsibilities, requirements, qualifications, benefits,
  whatsapp_number, contact_email, phone_number, published_date, status
)
select
  d.reference, d.title, d.slug,
  co.id, cat.id, cn.id, loc.id,
  d.employment_type::employment_type, d.experience_min, d.experience_max,
  d.salary_min, d.salary_max, d.salary_currency, d.salary_is_visible,
  d.description, d.responsibilities, d.requirements, d.qualifications, d.benefits,
  d.whatsapp_number, d.contact_email, d.phone_number,
  current_date - d.days_ago, 'published'
from (values
  ('GJH-100001','Senior Civil Engineer','senior-civil-engineer-riyadh','al-falak-engineering-group','civil','saudi-arabia','riyadh','full_time',5,9,12000,16000,'SAR',true,
   'Al Falak Engineering Group is seeking an experienced Senior Civil Engineer to lead structural design and site execution for large-scale commercial developments in Riyadh.',
   E'Lead civil design reviews for ongoing projects\nCoordinate with structural and MEP teams\nSupervise site engineers and monitor construction quality\nEnsure compliance with Saudi Building Code',
   E'Bachelor\'s degree in Civil Engineering\n5+ years GCC site experience\nProficiency in AutoCAD and Civil 3D\nValid SCE certification preferred',
   E'BSc Civil Engineering (accredited university)\nPMP certification is a plus',
   E'Company housing or housing allowance\nAnnual flight ticket\nMedical insurance for family',
   '966500000001','careers@alfalakengineering.example','966112220001',2),
  ('GJH-100002','Construction Site Supervisor','construction-site-supervisor-jeddah','gulf-horizon-construction','construction','saudi-arabia','jeddah','full_time',4,8,9000,12000,'SAR',true,
   'Gulf Horizon Construction is hiring a hands-on Site Supervisor to oversee daily operations on a mixed-use tower project in Jeddah.',
   E'Supervise daily site activities and subcontractors\nEnforce HSE standards on site\nTrack progress against project schedule\nReport daily to the Project Manager',
   E'Diploma or degree in Construction Management\n4+ years supervisory experience\nStrong knowledge of safety regulations',
   E'Diploma in Civil/Construction Engineering',
   E'Transportation provided\nOvertime pay\nEnd of service benefits',
   '966500000002','careers@gulfhorizon.example','966122220002',5),
  ('GJH-100003','QA/QC Engineer - Oil & Gas','qaqc-engineer-oil-gas-dammam','northstar-oil-gas-services','qa-qc','saudi-arabia','dammam','contract',3,6,11000,14000,'SAR',true,
   'NorthStar Oil & Gas Services requires a QA/QC Engineer for a 12-month contract supporting pipeline inspection and welding quality assurance in Dammam.',
   E'Conduct inspection of welding and piping works\nMaintain QA/QC documentation and NCRs\nLiaise with third-party inspectors\nEnsure compliance with API and ASME standards',
   E'Degree in Mechanical/Petroleum Engineering\nCSWIP or API 570/510 certification\n3+ years oil & gas QA/QC experience',
   E'BSc Mechanical Engineering\nCSWIP 3.1 certified',
   E'Camp accommodation\nTransportation\nContract completion bonus',
   '966500000003','hr@northstarog.example','966132220003',1),
  ('GJH-100004','HSE Officer','hse-officer-khobar','northstar-oil-gas-services','hse','saudi-arabia','khobar','full_time',2,5,7000,9500,'SAR',true,
   'We are looking for a proactive HSE Officer to support safety compliance across our operational sites in Khobar.',
   E'Conduct daily HSE inspections and toolbox talks\nInvestigate incidents and near-misses\nMaintain HSE records and reporting\nDeliver safety inductions for new staff',
   E'NEBOSH IGC certification\n2+ years HSE experience in industrial sites\nGood command of English and Arabic preferred',
   E'Diploma in Occupational Health & Safety\nNEBOSH IGC',
   E'Medical insurance\nAnnual leave 30 days\nAirfare allowance',
   '966500000004','hse.jobs@northstarog.example','966132220004',7),
  ('GJH-100005','Software Engineer (Full-Stack)','software-engineer-full-stack-dubai','technova-solutions','it-software','uae','dubai','full_time',3,6,14000,20000,'AED',true,
   'TechNova Solutions is expanding its Dubai engineering team and is hiring a Full-Stack Software Engineer to build products used across the Gulf region.',
   E'Develop and maintain web applications using React and Node.js\nCollaborate with product and design teams\nWrite clean, tested, maintainable code\nParticipate in code reviews and sprint planning',
   E'3+ years professional software development experience\nStrong knowledge of JavaScript/TypeScript, React, Node.js\nExperience with REST APIs and SQL databases',
   E'BSc in Computer Science or related field',
   E'Visa sponsorship\nHealth insurance\nHybrid work options\nAnnual performance bonus',
   '971500000005','jobs@technova.example','97142220005',0),
  ('GJH-100006','Registered Nurse - ICU','registered-nurse-icu-abu-dhabi','bright-path-healthcare','healthcare','uae','abu-dhabi','full_time',2,7,8000,12000,'AED',true,
   'Bright Path Healthcare is recruiting Registered Nurses for the ICU department of a leading hospital in Abu Dhabi.',
   E'Provide critical care nursing to ICU patients\nMonitor vital signs and administer medication\nCollaborate with physicians on care plans\nMaintain accurate patient documentation',
   E'DOH/HAAD license (or eligibility)\nBSc Nursing\n2+ years ICU experience',
   E'BSc Nursing\nBLS/ACLS certification',
   E'Housing allowance\nMedical coverage\nAnnual flight ticket\nEnd of service gratuity',
   '971500000006','recruitment@brightpath.example','97124220006',3),
  ('GJH-100007','Procurement Manager','procurement-manager-doha','apex-logistics-gulf','procurement','qatar','doha','full_time',6,10,16000,22000,'QAR',true,
   'Apex Logistics Gulf is seeking a Procurement Manager to lead strategic sourcing and vendor management for our Doha operations.',
   E'Develop and execute procurement strategy\nNegotiate contracts with key suppliers\nManage procurement team and budgets\nEnsure timely delivery of materials and services',
   E'6+ years procurement/supply chain experience\nStrong negotiation and vendor management skills\nExperience with ERP procurement systems',
   E'Bachelor\'s degree in Supply Chain, Business or related field\nCIPS certification preferred',
   E'Family medical insurance\nAnnual airfare for family\nSchooling allowance',
   '974500000007','careers@apexlogistics.example','97444220007',4),
  ('GJH-100008','Logistics Coordinator','logistics-coordinator-doha','apex-logistics-gulf','logistics','qatar','doha','full_time',2,5,7500,10000,'QAR',true,
   'Join Apex Logistics Gulf as a Logistics Coordinator managing freight scheduling and warehouse coordination in Doha.',
   E'Coordinate inbound and outbound shipments\nTrack shipment status and resolve delays\nLiaise with customs and freight forwarders\nMaintain logistics records',
   E'2+ years logistics or supply chain experience\nProficiency in MS Excel and logistics software\nStrong organizational skills',
   E'Diploma or degree in Logistics/Business',
   E'Transportation allowance\nMedical insurance\nPerformance bonus',
   '974500000008','careers@apexlogistics.example','97444220008',6),
  ('GJH-100009','Electrical Technician','electrical-technician-kuwait-city','prime-facilities-management','electrical','kuwait','kuwait-city','full_time',3,7,600,850,'KWD',true,
   'Prime Facilities Management requires an experienced Electrical Technician for facilities maintenance contracts across Kuwait City.',
   E'Perform preventive and corrective electrical maintenance\nTroubleshoot electrical faults in commercial buildings\nEnsure compliance with electrical safety codes\nMaintain maintenance logs',
   E'3+ years electrical maintenance experience\nDiploma in Electrical Engineering or equivalent\nKnowledge of low voltage systems',
   E'Diploma in Electrical Engineering',
   E'Accommodation provided\nTransportation\nAnnual leave with airfare',
   '965500000009','jobs@primefm.example','96522220009',8),
  ('GJH-100010','Mechanical Maintenance Engineer','mechanical-maintenance-engineer-kuwait-city','prime-facilities-management','mechanical','kuwait','kuwait-city','full_time',4,8,750,1000,'KWD',true,
   'Prime Facilities Management is hiring a Mechanical Maintenance Engineer to oversee HVAC and mechanical systems maintenance.',
   E'Manage preventive maintenance schedules for HVAC systems\nSupervise mechanical technicians\nRespond to breakdown maintenance requests\nEnsure spare parts inventory is maintained',
   E'BSc Mechanical Engineering\n4+ years facilities maintenance experience\nStrong leadership skills',
   E'BSc Mechanical Engineering',
   E'Medical insurance\nHousing allowance\nAnnual flight ticket',
   '965500000010','jobs@primefm.example','96522220010',10),
  ('GJH-100011','Front Office Manager','front-office-manager-manama','desert-rose-hospitality','hospitality','bahrain','manama','full_time',4,8,900,1300,'BHD',true,
   'Desert Rose Hospitality is looking for a polished Front Office Manager for a 5-star property in Manama.',
   E'Oversee front desk, reservations and guest services\nHandle escalated guest concerns professionally\nTrain and mentor front office staff\nMonitor occupancy and revenue reports',
   E'4+ years hotel front office experience\nExcellent communication and leadership skills\nExperience with Opera PMS preferred',
   E'Bachelor\'s degree in Hospitality Management',
   E'Duty meals\nMedical insurance\nDiscounted hotel stays worldwide',
   '973500000011','careers@desertrosehg.example','97317220011',12),
  ('GJH-100012','Accountant - General Ledger','accountant-general-ledger-manama','al-reem-financial-group','finance-accounting','bahrain','manama','full_time',2,5,700,1000,'BHD',true,
   'Al Reem Financial Group is hiring a detail-oriented Accountant to manage general ledger and monthly closing activities.',
   E'Prepare journal entries and reconcile accounts\nAssist with monthly and year-end closing\nSupport external audit requirements\nMaintain accurate financial records',
   E'2+ years accounting experience\nProficiency in Excel and accounting software\nBachelor\'s degree in Accounting or Finance',
   E'BSc Accounting/Finance\nCMA/ACCA in progress a plus',
   E'Medical insurance\nPerformance bonus\nProfessional development support',
   '973500000012','careers@alreemfinancial.example','97317220012',9),
  ('GJH-100013','Security Supervisor','security-supervisor-muscat','secureguard-services','security','oman','muscat','full_time',3,6,450,600,'OMR',true,
   'SecureGuard Services is hiring a Security Supervisor to manage guarding operations for a commercial complex in Muscat.',
   E'Supervise security guard teams across shifts\nConduct site inspections and incident reporting\nEnsure compliance with client security protocols\nTrain new security personnel',
   E'3+ years security supervision experience\nStrong communication and reporting skills\nPolice/security clearance required',
   E'High school diploma minimum\nSecurity supervisor certification preferred',
   E'Accommodation provided\nTransportation\nOvertime pay',
   '968500000013','jobs@secureguard.example','96824220013',11),
  ('GJH-100014','Architect - Design Lead','architect-design-lead-muscat','skyline-architects','architecture','oman','muscat','full_time',5,10,1100,1500,'OMR',true,
   'Skyline Architects is seeking a talented Design Lead Architect to drive concept and design development for hospitality and residential projects in Muscat.',
   E'Lead architectural design from concept to detailed design\nCoordinate with structural and MEP consultants\nPresent design concepts to clients\nMentor junior architects',
   E'5+ years architectural design experience\nProficiency in Revit and AutoCAD\nStrong portfolio of completed projects',
   E'Bachelor\'s or Master\'s degree in Architecture\nLicensed Architect preferred',
   E'Housing allowance\nMedical insurance\nAnnual flight ticket',
   '968500000014','careers@skylinearchitects.example','96824220014',14),
  ('GJH-100015','HR Business Partner','hr-business-partner-riyadh','al-waha-trading-llc','hr','saudi-arabia','riyadh','full_time',5,9,13000,17000,'SAR',true,
   'Al Waha Trading LLC is seeking an experienced HR Business Partner to support its Riyadh headquarters across recruitment, employee relations and policy.',
   E'Partner with department heads on workforce planning\nManage end-to-end recruitment for assigned business units\nHandle employee relations and grievance cases\nDrive HR policy compliance with Saudi Labor Law',
   E'5+ years HR generalist/business partner experience\nStrong knowledge of Saudi Labor Law\nExcellent interpersonal skills',
   E'Bachelor\'s degree in HR or Business Administration\nSHRM/CIPD certification preferred',
   E'Medical insurance\nAnnual flight ticket\nPerformance bonus',
   '966500000015','careers@alwahatrading.example','966112220015',13),
  ('GJH-100016','Delivery Driver (Light Vehicle)','delivery-driver-light-vehicle-dubai','al-waha-trading-llc','driving','uae','dubai','full_time',1,4,3500,4500,'AED',true,
   'Al Waha Trading LLC requires reliable Delivery Drivers with a valid UAE light vehicle license for daily distribution routes across Dubai.',
   E'Deliver goods to customers within assigned routes\nMaintain vehicle cleanliness and basic checks\nHandle delivery documentation and collections\nProvide courteous customer service',
   E'Valid UAE driving license (light vehicle)\n1+ years delivery driving experience\nFamiliarity with Dubai routes',
   E'High school certificate',
   E'Fuel allowance\nMedical insurance\nOvertime pay',
   '971500000016','careers@alwahatrading.example','97142220016',15),
  ('GJH-100017','Sales & Marketing Executive','sales-marketing-executive-dammam','al-waha-trading-llc','sales-marketing','saudi-arabia','dammam','full_time',2,5,8000,11000,'SAR',true,
   'Al Waha Trading LLC is hiring a driven Sales & Marketing Executive to grow its B2B client base across the Eastern Province.',
   E'Identify and pursue new business opportunities\nManage relationships with existing clients\nPrepare sales proposals and quotations\nAchieve monthly and quarterly sales targets',
   E'2+ years B2B sales experience in the GCC\nExcellent negotiation and presentation skills\nValid Saudi driving license',
   E'Bachelor\'s degree in Business, Marketing or related field',
   E'Commission on sales\nCompany vehicle\nMedical insurance',
   '966500000017','careers@alwahatrading.example','966132220017',16),
  ('GJH-100018','Operations Manager','operations-manager-abu-dhabi','prime-facilities-management','management','uae','abu-dhabi','full_time',8,14,22000,30000,'AED',true,
   'Prime Facilities Management is looking for a seasoned Operations Manager to oversee multi-site facilities management contracts in Abu Dhabi.',
   E'Oversee daily operations across multiple client sites\nManage P&L for the operations portfolio\nEnsure SLA and KPI compliance\nLead and develop site management teams',
   E'8+ years operations management experience, facilities management background preferred\nStrong financial and people management skills\nBachelor\'s degree required',
   E'Bachelor\'s degree in Business or Engineering\nMBA is a plus',
   E'Company car\nMedical insurance for family\nAnnual bonus scheme',
   '971500000018','careers@primefm.example','97124220018',18)
) as d(
  reference, title, slug, company_slug, category_slug, country_slug, location_slug,
  employment_type, experience_min, experience_max, salary_min, salary_max, salary_currency, salary_is_visible,
  description, responsibilities, requirements, qualifications, benefits,
  whatsapp_number, contact_email, phone_number, days_ago
)
join companies co on co.slug = d.company_slug
join categories cat on cat.slug = d.category_slug
join countries cn on cn.slug = d.country_slug
join locations loc on loc.slug = d.location_slug;
